// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8jwWCakDMVLZmcfoMYGRL0ymirp4-5k4',
    appId: '1:455280907863:web:0b7c81fbdfdd9a12dc3512',
    messagingSenderId: '455280907863',
    projectId: 'pasal-b84c5',
    authDomain: 'pasal-b84c5.firebaseapp.com',
    storageBucket: 'pasal-b84c5.firebasestorage.app',
    measurementId: 'G-QRLMVVYMWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWXicFcXvrBCY1JJGv7alm7DYcj5pzd8',
    appId: '1:455280907863:android:f45d64404a563fe7dc3512',
    messagingSenderId: '455280907863',
    projectId: 'pasal-b84c5',
    storageBucket: 'pasal-b84c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXMPNmM_A67POShge24QkmFueNRk5BSLk',
    appId: '1:455280907863:ios:6f76e762f4a8d299dc3512',
    messagingSenderId: '455280907863',
    projectId: 'pasal-b84c5',
    storageBucket: 'pasal-b84c5.firebasestorage.app',
    iosBundleId: 'com.akai.pasaleko.dev',
  );
}
