// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8rGb7_u188Jc3dntehn2I6ngGTcTuiw',
    appId: '1:149008175042:web:038fe104759460d487505b',
    messagingSenderId: '149008175042',
    projectId: 'pasaleko-pos-prod',
    authDomain: 'pasaleko-pos-prod.firebaseapp.com',
    storageBucket: 'pasaleko-pos-prod.firebasestorage.app',
    measurementId: 'G-1ZJPP0GEDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYfthXMBNJQtq_MJpLmJ0iyxbWcmw-xxo',
    appId: '1:149008175042:android:c4fd3218add2607387505b',
    messagingSenderId: '149008175042',
    projectId: 'pasaleko-pos-prod',
    storageBucket: 'pasaleko-pos-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtFa12k5woqp7kQxIkf0oNTal98Ft2Ig',
    appId: '1:149008175042:ios:c1cfc7887796d95487505b',
    messagingSenderId: '149008175042',
    projectId: 'pasaleko-pos-prod',
    storageBucket: 'pasaleko-pos-prod.firebasestorage.app',
    androidClientId: '149008175042-q1hni7j7n6pnicc7sb128oovc4ua2c30.apps.googleusercontent.com',
    iosClientId: '149008175042-4rvpr9ihc486b3a9bletq24j9r8pm74f.apps.googleusercontent.com',
    iosBundleId: 'com.akai.pasaleko',
  );
}
