name: pasale_register
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  get_it: any
  share_plus: any
  vibration: any
  camera: any
  audioplayers: any
  path_provider: any
  uuid: any
  device_info_plus: any
  shared_preferences: any
  mlkit_camera:
    path: ../pasale_mlkit_camera/packages/mlkit_camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: any
  fake_cloud_firestore: any

flutter:
  uses-material-design: true
  assets:
    - assets/seeded_products.json
    - assets/beep.mp3
